version: "3"
# https://blog.codeship.com/using-docker-compose-for-python-development/
services:
  app:
    build: .
    command: python src/run.py --restore-epd
    depends_on:
      - db
    volumes:
      - ./data:/usr/src/app/data
      - ./outputs:/usr/src/app/outputs
      - ./logs:/usr/src/app/logs
      - ./config:/usr/src/app/config
      - ./src:/usr/src/app/src

  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5442:5432"

volumes:
  db-data:
    driver: local
