version: "3"
# https://blog.codeship.com/using-docker-compose-for-python-development/
services:
  app:
    build: .
    command: bash
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres

  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5442:5432"

volumes:
  db-data:
    driver: local
